FROM registry.access.redhat.com/ubi8/python-312

WORKDIR /opt/app-root/

COPY . /opt/app-root

USER root

RUN dnf -y update && dnf install -y gcc gcc-c++ \
 && pip install uv

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

RUN --mount=type=cache,target=/.cache/uv \
    uv sync --frozen --no-install-project --no-dev

RUN --mount=type=cache,target=/.cache/uv \
    uv sync --frozen --no-dev

RUN chgrp -R root /opt/app-root/ && chmod -R g+rwx /opt/app-root/

EXPOSE 7720

USER 1001

CMD uv run . --host 0.0.0.0
