use std::{collections::BTreeSet, error::Error, fs, path::PathBuf};

use driver::{BuiltinActionCatalog, DriverActionCatalog};

fn render_union_type(name: &str, values: impl IntoIterator<Item = String>) -> String {
    let mut uniq = BTreeSet::new();
    for value in values {
        uniq.insert(value);
    }
    let body = if uniq.is_empty() {
        "never".to_string()
    } else {
        uniq.into_iter()
            .map(|value| format!("{value:?}"))
            .collect::<Vec<_>>()
            .join(" | ")
    };
    format!("export type {name} = {body};")
}

fn render_typescript_ids() -> String {
    let catalog = BuiltinActionCatalog::new();
    let action_union = render_union_type(
        "ActionId",
        catalog.list_actions().into_iter().map(|action| action.id),
    );
    let class_union = render_union_type(
        "ClassName",
        catalog.list_classes().into_iter().map(|class_info| class_info.name),
    );
    format!(
        r#"/* eslint-disable */
// This file is auto-generated by `cargo run --manifest-path app-gui/src-tauri/Cargo.toml --example gen_ids`.
// Do not edit by hand.

{action_union}
{class_union}
"#
    )
}

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let output_path = manifest_dir.join("../src/shared/generated/ids.ts");
    let ids = render_typescript_ids();
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&output_path, ids)?;
    println!("generated {}", output_path.display());
    Ok(())
}
