//! Compiled risc0 guest binary + image_id, generated by `risc0-build`.
//!
//! Exposes:
//! - `CRAFT_GUEST_ELF: &[u8]` — the RISC-V ELF
//! - `CRAFT_GUEST_ID: [u32; 8]` — the image_id (pinned in synchronizer + relayer)
//!
//! Plus a `CRAFT_GUEST_PATH: &str` for diagnostics.

include!(concat!(env!("OUT_DIR"), "/methods.rs"));

/// Image id rendered as a 64-char lowercase hex string. Use this to set the
/// `GUEST_IMAGE_ID` env var that the synchronizer + relayer expect.
pub fn image_id_hex() -> String {
    let mut s = String::with_capacity(64);
    for word in &CRAFT_GUEST_ID {
        // risc0 image_id words are u32 LE — convert to bytes BE for the
        // canonical hex form by swapping byte order.
        for b in word.swap_bytes().to_le_bytes() {
            s.push_str(&format!("{b:02x}"));
        }
    }
    s
}
