fn FindLog(action) {
    var log = action.output("Log");
}

fn BurnLogs(action) {
    var log00 = action.input("Log");
    var log01 = action.input("Log");
    var log02 = action.input("Log");
    var log03 = action.input("Log");
    var log04 = action.input("Log");
    var log05 = action.input("Log");
    var log06 = action.input("Log");
    var log07 = action.input("Log");
    var log08 = action.input("Log");
    var log09 = action.input("Log");
    var log10 = action.input("Log");
    var log11 = action.input("Log");
    var log12 = action.input("Log");
    var log13 = action.input("Log");
    var log14 = action.input("Log");
    var log15 = action.input("Log");
    var log16 = action.input("Log");
    var log17 = action.input("Log");
    var log18 = action.input("Log");
    var log19 = action.input("Log");
    var log20 = action.input("Log");
    var log21 = action.input("Log");
    var log22 = action.input("Log");
    var log23 = action.input("Log");
    var log24 = action.input("Log");
    var log25 = action.input("Log");
    var log26 = action.input("Log");
    var log27 = action.input("Log");
    var log28 = action.input("Log");
    var log29 = action.input("Log");
    var log30 = action.input("Log");
    var log31 = action.input("Log");
    var log32 = action.input("Log");
    var log33 = action.input("Log");
    var log34 = action.input("Log");
    var log35 = action.input("Log");
    var log36 = action.input("Log");
    var log37 = action.input("Log");
    var log38 = action.input("Log");
    var log39 = action.input("Log");
    var log40 = action.input("Log");
    var log41 = action.input("Log");
    var log42 = action.input("Log");
    var log43 = action.input("Log");
    var log44 = action.input("Log");
    var log45 = action.input("Log");
    var log46 = action.input("Log");
    var log47 = action.input("Log");
    var log48 = action.input("Log");
    var log49 = action.input("Log");
}
