#![allow(dead_code)]

use std::collections::BTreeSet;

use crate::action_spec;

fn render_union_type(name: &str, values: impl IntoIterator<Item = String>) -> String {
    let mut uniq = BTreeSet::new();
    for value in values {
        uniq.insert(value);
    }
    let body = if uniq.is_empty() {
        "never".to_string()
    } else {
        uniq.into_iter()
            .map(|value| format!("{value:?}"))
            .collect::<Vec<_>>()
            .join(" | ")
    };
    format!("export type {name} = {body};")
}

pub(crate) fn render_typescript_contracts() -> String {
    let action_union = render_union_type("ActionId", action_spec::action_ids());
    let class_union = render_union_type("ClassName", action_spec::class_names());
    format!(
        r#"/* eslint-disable */
// This file is auto-generated by `cargo run --manifest-path app-gui/src-tauri/Cargo.toml --bin gen_contracts`.
// Do not edit by hand.

{action_union}
{class_union}

export type Validity = "live" | "nullified";
export type MethodArgKind = "class";
export type ProofPhase = "hash" | "verify" | "nullify" | "commit";
export type ProofProgressStatus = "running" | "done";

export interface MethodArgPayload {{
  kind: MethodArgKind;
  label: ClassName;
  classHash: string;
}}

export interface ObjectMethodPayload {{
  methodName: string;
  cpuCost: string;
  readsBlock: boolean;
  args: MethodArgPayload[];
}}

export interface ClassMetaPayload {{
  name: ClassName;
  hash: string;
}}

export interface SourceActionMetaPayload {{
  name: ActionId;
  hash: string;
}}

export interface ItemStatPayload {{
  key: string;
  value: string;
  tone?: string;
}}

export interface InventoryItemPayload {{
  id: string;
  fileName: string;
  emoji: string;
  validity: Validity;
  stateRoot: string;
  nullifier?: string;
  classMeta: ClassMetaPayload;
  sourceAction?: SourceActionMetaPayload;
  description?: string;
  methods: ObjectMethodPayload[];
  stats: ItemStatPayload[];
}}

export interface RecipePayload {{
  id: ActionId;
  group: string;
  name: ActionId;
  emoji: string;
  hash: string;
  verb: ActionId;
  desc: string;
  cpu: string;
  readsBlock: boolean;
  args: MethodArgPayload[];
  unlocked: boolean;
}}

export interface LoadGuiBootstrapResult {{
  objects: InventoryItemPayload[];
  actions: RecipePayload[];
}}

export interface RunSdkActionArgInput {{
  objectPath: string;
  label?: string;
}}

export interface RunSdkActionInput {{
  actionId: ActionId;
  inputs: RunSdkActionArgInput[];
}}

export interface RunSdkActionResult {{
  ok: boolean;
  oldRoot: string;
  newRoot: string;
  outputFiles: string[];
  nullifiedFiles: string[];
  objects: InventoryItemPayload[];
}}

export interface DobjFileMetadata {{
  fileName: string;
  className: ClassName;
  validity: Validity;
}}

export interface RunSdkActionProgress {{
  runId: string;
  phase: ProofPhase;
  status: ProofProgressStatus;
  message: string;
  verifyIndex: number | null;
  detail: string | null;
  oldRoot: string | null;
  newRoot: string | null;
  outputFile: string | null;
}}

export interface CpuSample {{
  usagePct: number;
  totalCpuSecs: number;
}}

export interface AppSettingsPayload {{
  synchronizerApiUrl: string;
  relayerApiUrl: string;
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::render_typescript_contracts;

    #[test]
    fn contracts_generation_is_deterministic() {
        let first = render_typescript_contracts();
        let second = render_typescript_contracts();
        assert_eq!(first, second);
    }

    #[test]
    fn contracts_include_action_and_class_unions() {
        let contracts = render_typescript_contracts();
        assert!(contracts.contains("export type ActionId ="));
        assert!(contracts.contains("\"FindLog\""));
        assert!(contracts.contains("export type ClassName ="));
        assert!(contracts.contains("\"WoodPick\""));
    }
}
