#![allow(dead_code)]

use std::collections::BTreeSet;

use crate::action_spec;

fn render_union_type(name: &str, values: impl IntoIterator<Item = String>) -> String {
    let mut uniq = BTreeSet::new();
    for value in values {
        uniq.insert(value);
    }
    let body = if uniq.is_empty() {
        "never".to_string()
    } else {
        uniq.into_iter()
            .map(|value| format!("{value:?}"))
            .collect::<Vec<_>>()
            .join(" | ")
    };
    format!("export type {name} = {body};")
}

pub(crate) fn render_typescript_ids() -> String {
    let action_union = render_union_type("ActionId", action_spec::action_ids());
    let class_union = render_union_type("ClassName", action_spec::class_names());
    format!(
        r#"/* eslint-disable */
// This file is auto-generated by `cargo run --manifest-path app-gui/src-tauri/Cargo.toml --bin gen_ids`.
// Do not edit by hand.

{action_union}
{class_union}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::render_typescript_ids;

    #[test]
    fn ids_generation_is_deterministic() {
        let first = render_typescript_ids();
        let second = render_typescript_ids();
        assert_eq!(first, second);
    }

    #[test]
    fn ids_include_action_and_class_unions() {
        let ids = render_typescript_ids();
        assert!(ids.contains("export type ActionId ="));
        assert!(ids.contains("\"FindLog\""));
        assert!(ids.contains("export type ClassName ="));
        assert!(ids.contains("\"WoodPick\""));
    }
}
