//! Blob parser + risc0 receipt verifier.
//!
//! [`BlobParser`] is the trait the synchronizer's state machine consumes. The
//! production implementation is [`Risc0Verifier`], which:
//! 1. Strips the magic envelope to recover the bincode-serialized risc0
//!    `Receipt`.
//! 2. Calls `Receipt::verify(image_id)` to check the proof.
//! 3. Decodes the borsh-encoded [`txlib_core::abi::GuestJournal`] from the
//!    receipt journal.
//! 4. Returns a `Payload` populated from the journal.
//!
//! `MockBlobParser` accepts a JSON shape — used by integration tests that
//! don't want to spin up the prover. It still goes through the magic
//! envelope, but the "receipt" is just a JSON document we parse directly.
//! Replaces the pod2-era `MockBlobParser` of the same name.

use anyhow::{Context, Result, anyhow};
use risc0_zkvm::{Digest, Receipt};

use crate::payload::{Payload, decode_blob_envelope};
#[cfg(any(test, feature = "test-utils"))]
use txlib_core::Hash;
use txlib_core::abi::GuestJournal;

pub trait BlobParser: Send + Sync {
    /// Decode + verify one blob payload.
    ///
    /// - `Ok(Some(payload))`: blob was ours, the proof verified, and the
    ///   journal was decoded successfully.
    /// - `Ok(None)`: blob doesn't carry our magic envelope. Belongs to some
    ///   other application; silently skip.
    /// - `Err(_)`: blob *was* ours but verification failed. Caller logs.
    fn parse_blob(&self, bytes: &[u8]) -> Result<Option<Payload>>;
}

// ---------------------------------------------------------------------------
// Risc0Verifier — production
// ---------------------------------------------------------------------------

/// Verifies risc0 receipts produced by the unified action guest.
///
/// Constructed once at synchronizer startup with the pinned `image_id` of the
/// guest binary. `image_id` is generated by `risc0-build` at guest compile
/// time; the synchronizer reads it from a config file or constant.
pub struct Risc0Verifier {
    image_id: Digest,
}

impl Risc0Verifier {
    pub fn new(image_id: impl Into<Digest>) -> Self {
        Self {
            image_id: image_id.into(),
        }
    }

    pub fn from_words(words: [u32; 8]) -> Self {
        Self {
            image_id: Digest::from(words),
        }
    }

    pub fn image_id(&self) -> &Digest {
        &self.image_id
    }
}

impl BlobParser for Risc0Verifier {
    fn parse_blob(&self, bytes: &[u8]) -> Result<Option<Payload>> {
        let Some(receipt_bytes) = decode_blob_envelope(bytes)? else {
            return Ok(None);
        };

        let receipt: Receipt = bincode::deserialize(receipt_bytes)
            .context("failed to deserialize risc0 Receipt from blob payload")?;

        receipt
            .verify(self.image_id)
            .map_err(|e| anyhow!("risc0 receipt verification failed: {e}"))?;

        let journal_bytes = receipt.journal.bytes.as_slice();
        let journal: GuestJournal = borsh::from_slice(journal_bytes)
            .context("failed to borsh-decode GuestJournal from receipt journal")?;

        Ok(Some(Payload {
            tx_final: journal.tx_final,
            state_root_hash: journal.state_root_hash,
            nullifiers: journal.nullifiers,
            receipt_bytes: receipt_bytes.to_vec(),
        }))
    }
}

// ---------------------------------------------------------------------------
// MockBlobParser — for integration tests without the real prover
// ---------------------------------------------------------------------------

/// Test-only parser. Accepts a JSON shape inside the magic envelope:
/// ```json
/// { "tx_final": "0x...", "nullifiers": ["0x..."], "state_root_hash": "0x..." }
/// ```
/// Returns a `Payload` with empty `receipt_bytes`.
#[cfg(any(test, feature = "test-utils"))]
pub struct MockBlobParser;

#[cfg(any(test, feature = "test-utils"))]
#[derive(serde::Deserialize)]
struct MockProofJson {
    tx_final: Hash,
    nullifiers: Vec<Hash>,
    state_root_hash: Hash,
}

#[cfg(any(test, feature = "test-utils"))]
impl BlobParser for MockBlobParser {
    fn parse_blob(&self, bytes: &[u8]) -> Result<Option<Payload>> {
        let Some(receipt_bytes) = decode_blob_envelope(bytes)? else {
            return Ok(None);
        };
        let json: MockProofJson = match serde_json::from_slice(receipt_bytes) {
            Ok(j) => j,
            // Not our test format — treat as wrong-format and surface as None.
            Err(_) => return Ok(None),
        };
        Ok(Some(Payload {
            tx_final: json.tx_final,
            state_root_hash: json.state_root_hash,
            nullifiers: json.nullifiers,
            receipt_bytes: receipt_bytes.to_vec(),
        }))
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::payload::encode_blob_payload;
    use txlib_core::hash::sha256;

    fn json_blob(tx_final: Hash, nullifiers: &[Hash], state_root: Hash) -> Vec<u8> {
        let null_strs: Vec<String> = nullifiers
            .iter()
            .map(|h| format!("\"0x{}\"", hex_lower(h.as_bytes())))
            .collect();
        let s = format!(
            r#"{{"tx_final":"0x{}","nullifiers":[{}],"state_root_hash":"0x{}"}}"#,
            hex_lower(tx_final.as_bytes()),
            null_strs.join(","),
            hex_lower(state_root.as_bytes())
        );
        encode_blob_payload(s.as_bytes())
    }

    fn hex_lower(b: &[u8]) -> String {
        let mut s = String::with_capacity(b.len() * 2);
        for byte in b {
            s.push_str(&format!("{byte:02x}"));
        }
        s
    }

    #[test]
    fn mock_parser_roundtrip() {
        let parser = MockBlobParser;
        let tx = sha256(b"tx");
        let n = sha256(b"n");
        let sr = sha256(b"sr");
        let blob = json_blob(tx, &[n], sr);
        let payload = parser.parse_blob(&blob).unwrap().unwrap();
        assert_eq!(payload.tx_final, tx);
        assert_eq!(payload.nullifiers, vec![n]);
        assert_eq!(payload.state_root_hash, sr);
    }

    #[test]
    fn mock_parser_skips_wrong_magic() {
        let parser = MockBlobParser;
        // No magic envelope.
        let blob = br#"{"tx_final":"0x00","nullifiers":[],"state_root_hash":"0x00"}"#;
        assert!(parser.parse_blob(blob).unwrap().is_none());
    }

    #[test]
    fn mock_parser_skips_invalid_json_under_magic() {
        let parser = MockBlobParser;
        let blob = encode_blob_payload(b"not json");
        // Should silently skip, not error — caller decides what to do.
        assert!(parser.parse_blob(&blob).unwrap().is_none());
    }

    #[test]
    fn risc0_verifier_skips_non_magic_blobs() {
        let verifier = Risc0Verifier::from_words([0u32; 8]);
        let blob = b"not ours at all";
        assert!(verifier.parse_blob(blob).unwrap().is_none());
    }

    #[test]
    fn risc0_verifier_errors_on_garbage_after_magic() {
        let verifier = Risc0Verifier::from_words([0u32; 8]);
        let blob = encode_blob_payload(b"not a real receipt");
        // Bincode deserialize fails before reaching verify.
        assert!(verifier.parse_blob(&blob).is_err());
    }
}
